name: production
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm

steps:
  - name: build
    image: node:latest
    commands:
      - yarn install --production
      - yarn add @vue/cli-service
      - yarn run test:unit
